const appString = {
  pt: {
    home: "Home",
    about: "Sobre",
    searchSpecies: "Busca de Espécies",
    signIn: "Login",
    signOut: "Sair",
    email: "Email",
    password: "Senha",
    search: "Buscar",
    forgotPassword: "Esqueceu a senha?",
    loginWelcome: "Seja Bem-vindo!",
    registerWelcome: "Cadastro",
    location: "Localização",
    taxonName: "Nome científico",
    order: "Ordenar",
    invalidCredentials: "Email ou senha inválidos",
    invalidMushroom: "ID inválido ou já cadastrado",
    mushroomCreated: "Espécie cadastrada com sucesso",
    invalidPasswordConfirm: "Senhas não conferem",
    register: "Cadastre-se",
    registerMushroom: "Cadastrar cogumelo",
    curateMushrooms: "Revisar cogumelos",
    manageUsers: "Gerenciar curadores",
    curateObservations: "Revisar observações",
    projectName: "BEM",
    mushroomCuration: "Curadoria de espécies",
    observationCuration: "Curadoria de observações",
    approve: "Aprovar",
    reprove: "Reprovar",
  },
};

export default appString;
