server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  application:
    name: mangue-bem-api

api:
  security:
    jwt:
      secret: ${API_SECURITY_JWT_SECRET}
      issuer: bem-api

integration:
  specieslink:
    apikey: ${INTEGRATION_SPECIESLINK_APIKEY}
  iucnredlist:
    token: ${INTEGRATION_IUCNREDLIST_TOKEN}

logging:
  level:
    org:
      hibernate:
        SQL: debug
      type:
        descriptor:
          sql: trace

log4j:
  logger:
    org:
    hibernate:
      SQL: debug
    type: trace
